name: arretadas
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
   
  mapbox_gl: ^0.0.1
  flutter_gallery: ^2.4.0+20400
  
  flutter:
    sdk: flutter
  
    
  
  flutter_map: any
  flutter_map_marker_cluster: any
  flutter_map_location_marker: any 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: any
  url_launcher: 5.4.2
  geolocator: ^5.1.5
  #http: ^0.12.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: # added


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Exo
      fonts:
        - asset: fonts/Exo-Regular.otf
          style: normal
        - asset: fonts/Exo-Regular.ttf
          weight: 700
    
    - family: Rounded
      fonts:
        - asset: fonts/Rounded_Elegance.ttf
          
    - family: Salted
      fonts:
        - asset: fonts/Saltedcaramel.ttf
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
